language: node_js
node_js:
  - "10"
cache: npm

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - travis_wait ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
